name: Deploy Hostings

on:
  push:
    branches:
      - main
    paths:
      - 'hosting/**'
      - '.github/**'
  pull_request:
    branches:
      - main
    paths:
      - 'hosting/**'
      - '.github/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Deploy hosting
        run: |
          cd hosting
          npm ci
          npm run build
          export FIREBASE_TOKEN=${{ secrets.FIREBASE_SERVICE_ACCOUNT_LINK_SHORTER_TQBDEV }}
          npm run deploy