name: Deploy Hostings

on:
  push:
    branches:
      - main
    paths:
      - 'hosting/**'
      - '.github/**'
  pull_request:
    branches:
      - main
    paths:
      - 'hosting/**'
      - '.github/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Deploy hosting
        run: |
          cd hosting
          npm install
          npm run build
          npm run deploy